The difference between how a data is represented in Numpy vs how it is done in tensorflow

In [13]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras import Sequential
from keras.layers import Dense

In [4]:
x=np.array([[200,17]]) #This represents one row

In [5]:
x

array([[200,  17]])

In [6]:
x=np.array([200,200]) # This represents one column

In [7]:
x

array([200, 200])

In [8]:
x=np.array(
    [[1,2,3],
      [4,5,6]]
) #2x3 Matrix

In [9]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
x=np.array([[200],[17]])

In [12]:
x

array([[200],
       [ 17]])

In [17]:
x=np.array([[200,17]])
layer_1=Dense(units=3,activation='sigmoid')
a=layer_1(x)
a


<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 1.]], dtype=float32)>

In [18]:
a.numpy()

array([[0., 0., 1.]], dtype=float32)