This notebook will try to implement the ideas in this lecture: https://www.coursera.org/learn/advanced-learning-algorithms/lecture/rJMKC/inference-in-code

In [7]:
import pandas as pd
import numpy as np
import tensorflow
from keras import Sequential
from keras.layers import Dense

In [9]:
x=np.array([[200,17.0]]) # let us define an input array

In [5]:
x

array([[200.,  17.]])

Let us define the first layer of the neural network with 3 neurons and the input shape is [2,1]

In [15]:
layer_1=Dense(units=3,input_shape=[2,1],activation='sigmoid')
a1=layer_1(x)
print(a1)
layer_2=Dense(units=1,activation='sigmoid')
a2=layer_2(a1)
print(a2)

tf.Tensor([[1.9650371e-36 0.0000000e+00 1.7482270e-21]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.5]], shape=(1, 1), dtype=float32)


In [8]:
model=Sequential(Dense(units=3,input_shape=[2,1])) #first layer of the nueral network wh

In [ ]:
model.com